<a href="https://colab.research.google.com/github/leesangh92/python/blob/main/(21.5.18).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
t = [i * 3 for i in range(1, 11)]

In [ ]:
a = [1, 2, 3]
b = [4, 5, 6]
c = [a, b]

In [ ]:
np1 = np.array(t)

In [ ]:
type(np1)

numpy.ndarray

In [ ]:
np1

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [ ]:
np1 + 1

array([ 4,  7, 10, 13, 16, 19, 22, 25, 28, 31])

In [ ]:
np1 + 100

array([103, 106, 109, 112, 115, 118, 121, 124, 127, 130])

In [ ]:
np1.dtype # data 타입, int64의 크기(2 ** 64, 약 -922경 ~ 약 922경)

dtype('int64')

In [ ]:
2 ** 8 ## 8 bit = 1 byte
2 ** 16 ## 2 byte
2 ** 32 ## 4 byte
2 ** 64 ## 8 byte, 1844경 6744조 737억 955만 1616

18446744073709551616

In [ ]:
np1.shape

(10,)

In [ ]:
np1.mean()

16.5

In [ ]:
dir(np1)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [ ]:
np1.nbytes ##  8 byte 10개

80

In [ ]:
np1.itemsize ## item 하나는 8 bytes

8

In [ ]:
a

[1, 2, 3]

In [ ]:
b

[4, 5, 6]

In [ ]:
c

[[1, 2, 3], [4, 5, 6]]

In [ ]:
np2 = np.array(c)

In [ ]:
np2.shape ## 행렬

(2, 3)

In [ ]:
np2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np2.nbytes ## 8 bytes 6개

48

In [ ]:
np2[0]

array([1, 2, 3])

In [ ]:
k = np2[0]

In [ ]:
k.shape

(3,)

In [ ]:
np2[1, 2]

6

In [ ]:
np2[1][2]

6

In [ ]:
np2 + 10

array([[11, 12, 13],
       [14, 15, 16]])

In [ ]:
np2.T ## 전치 행렬

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np1. mean()

16.5

In [ ]:
np1.min()

3

In [ ]:
np1.max()

30

In [ ]:
np2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np2.sum()

21

In [ ]:
np2.sum(axis = 0) ## 열(i, axis = 0)의 합

array([5, 7, 9])

In [ ]:
np2.sum(axis = 1) ## 행(j, axis = 1)의 합

array([ 6, 15])

In [ ]:
np2.shape # 2차원 행렬의shape에서는 행과 열을 나타낸다

(2, 3)

In [ ]:
t1 = [i for i in range(2, 21, 2)]
t2 = [i * 3 for i in range(1, 11)]
t3 = [i for i in range(5, 51, 5)]

In [ ]:
t1, t2, t3

([2, 4, 6, 8, 10, 12, 14, 16, 18, 20],
 [3, 6, 9, 12, 15, 18, 21, 24, 27, 30],
 [5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [ ]:
tt = [t1, t2, t3]
np22 = np.array(tt)

In [ ]:
tt

[[2, 4, 6, 8, 10, 12, 14, 16, 18, 20],
 [3, 6, 9, 12, 15, 18, 21, 24, 27, 30],
 [5, 10, 15, 20, 25, 30, 35, 40, 45, 50]]

In [ ]:
np22

array([[ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50]])

In [ ]:
type(tt)

list

In [ ]:
type(np22)

numpy.ndarray

In [ ]:
np22.sum()

550

In [ ]:
np22[0].sum()

110

In [ ]:
np22[1].sum()

165

In [ ]:
np22[2].sum()

275

In [ ]:
np22.sum(axis = 1)

array([110, 165, 275])

In [ ]:
np22.sum(axis = 0)

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [ ]:
np23 = np22.T

In [ ]:
np23

array([[ 2,  3,  5],
       [ 4,  6, 10],
       [ 6,  9, 15],
       [ 8, 12, 20],
       [10, 15, 25],
       [12, 18, 30],
       [14, 21, 35],
       [16, 24, 40],
       [18, 27, 45],
       [20, 30, 50]])

In [ ]:
np23.min()

2

In [ ]:
np23.max()

50

In [ ]:
np23.min(axis = 1)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
x = np23.min(axis = 0)
x.shape ## 1차원 함수의 shape는 행이나 열의 개수를 나타낸다

(3,)

In [ ]:
x = np23.min(axis = 1)
x.shape

(10,)

In [ ]:
np23.min(axis = 0)

array([2, 3, 5])

In [ ]:
np23.max(axis =0)

array([20, 30, 50])

In [ ]:
np23.max(axis = 1)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [ ]:
np23.shape

(10, 3)

In [ ]:
np23.reshape(5, 6) # 행렬 변경

array([[ 2,  3,  5,  4,  6, 10],
       [ 6,  9, 15,  8, 12, 20],
       [10, 15, 25, 12, 18, 30],
       [14, 21, 35, 16, 24, 40],
       [18, 27, 45, 20, 30, 50]])

In [ ]:
np23.reshape(2, 15)

array([[ 2,  3,  5,  4,  6, 10,  6,  9, 15,  8, 12, 20, 10, 15, 25],
       [12, 18, 30, 14, 21, 35, 16, 24, 40, 18, 27, 45, 20, 30, 50]])

In [ ]:
np23.reshape(7, 4)

ValueError: ignored

In [ ]:
np23.reshape(6, 6)

ValueError: ignored

In [ ]:
np24 = np.array([i for i in range(1, 25)])

In [ ]:
np24

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [ ]:
np24.reshape(2, 12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
np24.reshape(4, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [ ]:
np11 = np.array([2, 4, 6, 8, 10])

In [ ]:
np11.nbytes

40

In [ ]:
np11.dtype ## 2 ** 64 = 8 bytes, 정수 자료형의 기본 저장 크기 8 bytes

dtype('int64')

In [ ]:
np12 = np.array([2, 4, 6, 8, 10], dtype=np.int16) ## 2 ** 16 = 2 bytes로 변환

크기 변환을 통해 메모리를 정돈 할 수 있어서 처리 속도가 빠르다 // 연속적인 메모리 정리를 통해 속도 향상 // numpy는 내부적으로 데이터를 다른 내장 파이썬 객체와 구분된 연속된 메모리 블록에 저장한다.

In [ ]:
np11.nbytes ## 8 bytes * 5

40

In [ ]:
np12.nbytes ## 2 bytes * 5

10

In [ ]:
np11.itemsize ## 8 bytes

8

In [ ]:
np12.itemsize ## 2bytes, 크기가 지정한 bytes 보다 크다면 에러

2

In [ ]:
np200 = np.array([2.3, 4.5, 6.7])

In [ ]:
np200.dtype

dtype('float64')

In [ ]:
np200.nbytes

24

In [ ]:
np200.itemsize

8

In [ ]:
np200 = np.array([2.3, 4.5, 6.7], dtype = np.float32)

In [ ]:
np200.nbytes

12

In [ ]:
np200 = np.array([2.3, 4.5, 6.7], dtype = np.float16)

In [ ]:
np200.nbytes

6

In [ ]:
np200.itemsize

2

In [ ]:
np13 = np.array([2, 4, 5], dtype = 'uint') # unsigned unit 정하지 않은

In [ ]:
np13

array([ 1,  2,  3,  9,  9, 11, 12,  8,  9, 10])

## 복소수도 처리 가능

In [ ]:
np.empty((7, 2))

array([[4.65291134e-310, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 7.49959658e+295]])

In [ ]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1, 6)

array([1, 2, 3, 4, 5])

In [ ]:
np.arange(1, 20, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

broadcasting을 가능하게 해준다

행 단위, 열 단위, 인수 단위 사칙연산 가능

In [ ]:
np11 = np.array([2, 4, 6, 8], dtype = np.int16)
np12 = np.array([3, 6, 9, 12, 15], dtype = np.int16)

In [ ]:
np11.shape

(4,)

In [ ]:
np11 += 5

In [ ]:
np11

array([ 7,  9, 11, 13], dtype=int16)

In [ ]:
np11 > 10

array([False, False,  True,  True])

In [ ]:
np11 == 11

array([False, False,  True, False])

In [ ]:
np11.__le__(9)

array([ True,  True, False, False])

In [ ]:
np11 < 9

array([ True, False, False, False])

In [ ]:
np11.size

4

In [ ]:
np11.nbytes

8

In [ ]:
np11.itemsize

2

In [ ]:
np13 = np.arange(1, 11)

In [ ]:
np13

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np13[3:7] + 5

array([ 9, 10, 11, 12])

In [ ]:
np13

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np13[3:7] += 5

In [ ]:
np13

array([ 1,  2,  3,  9, 10, 11, 12,  8,  9, 10])

In [ ]:
np13[4] = 9

In [ ]:
np13

array([ 1,  2,  3,  9,  9, 11, 12,  8,  9, 10])

In [ ]:
n1 = [1, 2, 3]
n2 = [2, 4, 6, 8, 10]
np2 = np.array([n1, n2])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  This is separate from the ipykernel package so we can avoid doing imports until


In [ ]:
np2 = np.arange(1, 16)

In [ ]:
np2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
np2.reshape(3, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
np35 = np2.reshape(3, 5)

In [ ]:
np35

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
np351 = np23[:, :2]

In [ ]:
np351

array([[ 1,  2],
       [ 6,  7],
       [11, 12]])

In [ ]:
np352 = np23[:][:][:][:][:2]

In [ ]:
np352

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
np3 = np.arange(1, 25)

In [ ]:
np3.ndim

1

In [ ]:
np3.shape

(24,)

In [ ]:
np33 = np.random.randn(24)

In [ ]:
np33.shape

(24,)

In [ ]:
np33

array([ 1.37208621,  0.28486849,  1.13726067, -0.48657995, -1.03598131,
        0.71575847,  1.60921816,  1.2839594 , -0.82174599,  0.74798382,
       -0.32065558,  0.2946956 , -0.48936985, -0.63670802, -1.16998986,
        0.70807273,  1.71491349,  0.40551782, -1.13769284, -0.0847985 ,
       -1.19546267, -0.3495489 ,  0.58819412,  1.34087501])

In [ ]:
np33 * 100

array([ 137.20862084,   28.48684889,  113.72606677,  -48.6579945 ,
       -103.59813102,   71.57584725,  160.92181583,  128.3959396 ,
        -82.17459942,   74.79838188,  -32.06555817,   29.46956018,
        -48.93698513,  -63.67080185, -116.9989858 ,   70.80727263,
        171.49134944,   40.55178212, -113.76928358,   -8.47985038,
       -119.54626711,  -34.95489028,   58.81941249,  134.08750067])

In [ ]:
np33.reshape(2, 3, 4)

array([[[ 1.37208621,  0.28486849,  1.13726067, -0.48657995],
        [-1.03598131,  0.71575847,  1.60921816,  1.2839594 ],
        [-0.82174599,  0.74798382, -0.32065558,  0.2946956 ]],

       [[-0.48936985, -0.63670802, -1.16998986,  0.70807273],
        [ 1.71491349,  0.40551782, -1.13769284, -0.0847985 ],
        [-1.19546267, -0.3495489 ,  0.58819412,  1.34087501]]])

In [ ]:
np3 = np.arange(10, 241, 10)

In [ ]:
np3.ndim

1

In [ ]:
np3

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240])

In [ ]:
np3.shape

(24,)

In [ ]:
np33 = np3.reshape(2, 12)

In [ ]:
np33.ndim

2

In [ ]:
np33

array([[ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120],
       [130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240]])

In [ ]:
np333 = np33.reshape(2, 3, 4)

In [ ]:
np333.ndim

3

In [ ]:
np333.shape

(2, 3, 4)

In [ ]:
np333

array([[[ 10,  20,  30,  40],
        [ 50,  60,  70,  80],
        [ 90, 100, 110, 120]],

       [[130, 140, 150, 160],
        [170, 180, 190, 200],
        [210, 220, 230, 240]]])

In [ ]:
np333[0][0][2]

30

In [ ]:
np333[0][2]

array([ 90, 100, 110, 120])

In [ ]:
np333[1:, 1:, :2]

array([[[170, 180],
        [210, 220]]])

In [ ]:
np64 = np333.reshape(6, 4)

In [ ]:
np64

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120],
       [130, 140, 150, 160],
       [170, 180, 190, 200],
       [210, 220, 230, 240]])

In [ ]:
np64[1:5, 2:]

array([[ 70,  80],
       [110, 120],
       [150, 160],
       [190, 200]])

In [ ]:
np4444 = np333.reshape(2, 3, 2, 2)

In [ ]:
np4444.ndim

4

In [ ]:
np4444.shape

(2, 3, 2, 2)

In [ ]:
np4444

array([[[[ 10,  20],
         [ 30,  40]],

        [[ 50,  60],
         [ 70,  80]],

        [[ 90, 100],
         [110, 120]]],


       [[[130, 140],
         [150, 160]],

        [[170, 180],
         [190, 200]],

        [[210, 220],
         [230, 240]]]])

▶ 5월18일 도전 과제

1) 구구단을 2차원 배열로 만드시오. gdan
2) int16으로 자료형을 변경하시오.
 
3) 3단에만 50을 더하시오.
4) 5단에만 100을 곱하시오.
5) 모양을 어떤 형태든 다르게 변경하시오.

In [ ]:
dan = np.array([i for i in range(1, 10)])

In [ ]:
dan

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
g = [i * dan for i in range(1, 10)]

In [ ]:
g

[array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 2,  4,  6,  8, 10, 12, 14, 16, 18]),
 array([ 3,  6,  9, 12, 15, 18, 21, 24, 27]),
 array([ 4,  8, 12, 16, 20, 24, 28, 32, 36]),
 array([ 5, 10, 15, 20, 25, 30, 35, 40, 45]),
 array([ 6, 12, 18, 24, 30, 36, 42, 48, 54]),
 array([ 7, 14, 21, 28, 35, 42, 49, 56, 63]),
 array([ 8, 16, 24, 32, 40, 48, 56, 64, 72]),
 array([ 9, 18, 27, 36, 45, 54, 63, 72, 81])]

In [ ]:
gdan = np.array([i * dan for i in range(1, 10)], dtype = np.int16)

In [ ]:
gdan

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 9, 18, 27, 36, 45, 54, 63, 72, 81]], dtype=int16)

In [ ]:
gdan[2] + 50

array([53, 56, 59, 62, 65, 68, 71, 74, 77], dtype=int16)

In [ ]:
gdan[4] * 100

array([ 500, 1000, 1500, 2000, 2500, 3000, 3500, 4000, 4500], dtype=int16)

In [ ]:
gdan.reshape(1, 81)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9,  2,  4,  6,  8, 10, 12, 14,
        16, 18,  3,  6,  9, 12, 15, 18, 21, 24, 27,  4,  8, 12, 16, 20,
        24, 28, 32, 36,  5, 10, 15, 20, 25, 30, 35, 40, 45,  6, 12, 18,
        24, 30, 36, 42, 48, 54,  7, 14, 21, 28, 35, 42, 49, 56, 63,  8,
        16, 24, 32, 40, 48, 56, 64, 72,  9, 18, 27, 36, 45, 54, 63, 72,
        81]], dtype=int16)